import { Match } from './../../entities/match.entity';
import { MatchDto } from './../../dto/match.dto';
import { NationalTeamRequestDto } from './../../dto/national-team.request.dto';
import { NationalTeam } from './../../entities/national-team.entity';
// import { GetStandingsResponseDto } from './dto/get-standings.response.dto';
// import { GetMatchesByRoundResponseDto } from './dto/get-matches-by-round.response.dto';
import { HttpService } from '@nestjs/axios';
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
// import { lastValueFrom } from 'rxjs';
// import { configService } from 'src/config/config.service';

@Injectable()
export class WorldCupService {
  constructor(
    private readonly httpService: HttpService,
    @InjectRepository(NationalTeam)
    private readonly nationalTeamRepository: Repository<NationalTeam>,
    @InjectRepository(Match)
    private readonly matchRepository: Repository<Match>,
  ) {}

  async getStandings() {
    // const response = await lastValueFrom(
    //   this.httpService.get(`${configService.getValue('STANDINGS')}`),
    // );

    // const data: GetStandingsResponseDto = response.data;
    // return data;

    const response = {
      standings: [
        {
          tournament: {
            name: 'World Cup, Group A',
            slug: 'world-cup-group-a',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 549,
            id: 3954,
          },
          type: 'total',
          name: 'Group A',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Ecuador',
                slug: 'ecuador',
                shortName: 'Ecuador',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 29169,
                nameCode: 'ECU',
                ranking: 44,
                disabled: false,
                national: true,
                type: 0,
                id: 4757,
                teamColors: {
                  primary: '#ffff00',
                  secondary: '#000063',
                  text: '#000063',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708993,
            },
            {
              team: {
                name: 'Netherlands',
                slug: 'netherlands',
                shortName: 'Netherlands',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 147330,
                nameCode: 'NED',
                ranking: 8,
                disabled: false,
                national: true,
                type: 0,
                id: 4705,
                teamColors: {
                  primary: '#ff6600',
                  secondary: '#281fe0',
                  text: '#281fe0',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708994,
            },
            {
              team: {
                name: 'Qatar',
                slug: 'qatar',
                shortName: 'Qatar',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 13036,
                nameCode: 'QAT',
                ranking: 49,
                national: true,
                type: 0,
                id: 4792,
                teamColors: {
                  primary: '#660000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708995,
            },
            {
              team: {
                name: 'Senegal',
                slug: 'senegal',
                shortName: 'Senegal',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 80038,
                nameCode: 'SEN',
                ranking: 18,
                disabled: false,
                national: true,
                type: 0,
                id: 4739,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#047151',
                  text: '#047151',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708996,
            },
          ],
          id: 87801,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group B',
            slug: 'world-cup-group-b',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 548,
            id: 3955,
          },
          type: 'total',
          name: 'Group B',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'England',
                slug: 'england',
                shortName: 'England',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 276219,
                nameCode: 'ENG',
                ranking: 5,
                national: true,
                type: 0,
                id: 4713,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#cc0000',
                  text: '#cc0000',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708997,
            },
            {
              team: {
                name: 'Iran',
                slug: 'iran',
                shortName: 'Iran',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 32163,
                nameCode: 'IRN',
                ranking: 23,
                national: true,
                type: 0,
                id: 4766,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#cc0000',
                  text: '#cc0000',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708998,
            },
            {
              team: {
                name: 'USA',
                slug: 'usa',
                shortName: 'USA',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 39017,
                nameCode: 'USA',
                ranking: 14,
                disabled: false,
                national: true,
                type: 0,
                id: 4724,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#ff0000',
                  text: '#ff0000',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 708999,
            },
            {
              team: {
                name: 'Wales',
                slug: 'wales',
                shortName: 'Wales',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 45040,
                nameCode: 'WAL',
                ranking: 19,
                disabled: false,
                national: true,
                type: 0,
                id: 4702,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#00813c',
                  text: '#00813c',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709000,
            },
          ],
          id: 87802,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group C',
            slug: 'world-cup-group-c',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 547,
            id: 3956,
          },
          type: 'total',
          name: 'Group C',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Argentina',
                slug: 'argentina',
                shortName: 'Argentina',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 393806,
                nameCode: 'ARG',
                ranking: 3,
                national: true,
                type: 0,
                id: 4819,
                teamColors: {
                  primary: '#66ccff',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709001,
            },
            {
              team: {
                name: 'Mexico',
                slug: 'mexico',
                shortName: 'Mexico',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 56063,
                nameCode: 'MEX',
                ranking: 12,
                national: true,
                type: 0,
                id: 4781,
                teamColors: {
                  primary: '#1a4d3e',
                  secondary: '#960000',
                  text: '#960000',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709002,
            },
            {
              team: {
                name: 'Poland',
                slug: 'poland',
                shortName: 'Poland',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 88729,
                nameCode: 'POL',
                ranking: 26,
                disabled: false,
                national: true,
                type: 0,
                id: 4703,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#ff0000',
                  text: '#ff0000',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709003,
            },
            {
              team: {
                name: 'Saudi Arabia',
                slug: 'saudi-arabia',
                shortName: 'Saudi Arabia',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 21522,
                nameCode: 'KSA',
                ranking: 53,
                national: true,
                type: 0,
                id: 4834,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#008000',
                  text: '#008000',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709004,
            },
          ],
          id: 87803,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group D',
            slug: 'world-cup-group-d',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 546,
            id: 3957,
          },
          type: 'total',
          name: 'Group D',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Australia',
                slug: 'australia',
                shortName: 'Australia',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 17309,
                nameCode: 'AUS',
                ranking: 39,
                national: true,
                type: 0,
                id: 4741,
                teamColors: {
                  primary: '#ffcc00',
                  secondary: '#2d324b',
                  text: '#2d324b',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709005,
            },
            {
              team: {
                name: 'Denmark',
                slug: 'denmark',
                shortName: 'Denmark',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 67654,
                nameCode: 'DEN',
                ranking: 10,
                disabled: false,
                national: true,
                type: 0,
                id: 4476,
                teamColors: {
                  primary: '#cc0000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709006,
            },
            {
              team: {
                name: 'France',
                slug: 'france',
                shortName: 'France',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 298495,
                nameCode: 'FRA',
                ranking: 4,
                disabled: false,
                national: true,
                type: 0,
                id: 4481,
                teamColors: {
                  primary: '#01509e',
                  secondary: '#e30613',
                  text: '#e30613',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709007,
            },
            {
              team: {
                name: 'Tunisia',
                slug: 'tunisia',
                shortName: 'Tunisia',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 44326,
                nameCode: 'TUN',
                ranking: 30,
                disabled: false,
                national: true,
                type: 0,
                id: 4729,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#cc0033',
                  text: '#cc0033',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709008,
            },
          ],
          id: 87804,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group E',
            slug: 'world-cup-group-e',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 545,
            id: 3958,
          },
          type: 'total',
          name: 'Group E',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Costa Rica',
                slug: 'costa-rica',
                shortName: 'Costa Rica',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 17002,
                nameCode: 'CRC',
                ranking: 34,
                disabled: false,
                national: true,
                type: 0,
                id: 4756,
                teamColors: {
                  primary: '#ed1c24',
                  secondary: '#2366b3',
                  text: '#2366b3',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709009,
            },
            {
              team: {
                name: 'Germany',
                slug: 'germany',
                shortName: 'Germany',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 249619,
                nameCode: 'GER',
                ranking: 11,
                national: true,
                type: 0,
                id: 4711,
                teamColors: {
                  primary: '#ffffff',
                  secondary: '#000000',
                  text: '#000000',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709010,
            },
            {
              team: {
                name: 'Japan',
                slug: 'japan',
                shortName: 'Japan',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 28568,
                nameCode: 'JPN',
                ranking: 24,
                national: true,
                type: 0,
                id: 4770,
                teamColors: {
                  primary: '#000080',
                  secondary: '#ed1b24',
                  text: '#ed1b24',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709011,
            },
            {
              team: {
                name: 'Spain',
                slug: 'spain',
                shortName: 'Spain',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 273147,
                nameCode: 'ESP',
                ranking: 6,
                national: true,
                type: 0,
                id: 4698,
                teamColors: {
                  primary: '#cc0000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709012,
            },
          ],
          id: 87805,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group F',
            slug: 'world-cup-group-f',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 544,
            id: 3959,
          },
          type: 'total',
          name: 'Group F',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Belgium',
                slug: 'belgium',
                shortName: 'Belgium',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 181693,
                nameCode: 'BEL',
                ranking: 2,
                national: true,
                type: 0,
                id: 4717,
                teamColors: {
                  primary: '#ff0033',
                  secondary: '#000000',
                  text: '#000000',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709013,
            },
            {
              team: {
                name: 'Canada',
                slug: 'canada',
                shortName: 'Canada',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 18869,
                nameCode: 'CAN',
                ranking: 43,
                national: true,
                type: 0,
                id: 4752,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709014,
            },
            {
              team: {
                name: 'Croatia',
                slug: 'croatia',
                shortName: 'Croatia',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 122675,
                nameCode: 'CRO',
                ranking: 15,
                disabled: false,
                national: true,
                type: 0,
                id: 4715,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709015,
            },
            {
              team: {
                name: 'Morocco',
                slug: 'morocco',
                shortName: 'Morocco',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 83019,
                nameCode: 'MAR',
                ranking: 22,
                disabled: false,
                national: true,
                type: 0,
                id: 4778,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#006600',
                  text: '#006600',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709016,
            },
          ],
          id: 87806,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group G',
            slug: 'world-cup-group-g',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 543,
            id: 3960,
          },
          type: 'total',
          name: 'Group G',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Brazil',
                slug: 'brazil',
                shortName: 'Brazil',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 407523,
                nameCode: 'BRA',
                ranking: 1,
                national: true,
                type: 0,
                id: 4748,
                teamColors: {
                  primary: '#ffff00',
                  secondary: '#009933',
                  text: '#009933',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709017,
            },
            {
              team: {
                name: 'Cameroon',
                slug: 'cameroon',
                shortName: 'Cameroon',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 45784,
                nameCode: 'CMR',
                ranking: 38,
                disabled: false,
                national: true,
                type: 0,
                id: 4751,
                teamColors: {
                  primary: '#006633',
                  secondary: '#d01124',
                  text: '#d01124',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709018,
            },
            {
              team: {
                name: 'Serbia',
                slug: 'serbia',
                shortName: 'Serbia',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 54322,
                nameCode: 'SRB',
                ranking: 25,
                national: true,
                type: 0,
                id: 6355,
                teamColors: {
                  primary: '#ff0033',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709019,
            },
            {
              team: {
                name: 'Switzerland',
                slug: 'switzerland',
                shortName: 'Switzerland',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 56160,
                nameCode: 'SUI',
                ranking: 16,
                disabled: false,
                national: true,
                type: 0,
                id: 4699,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#ffffff',
                  text: '#ffffff',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709020,
            },
          ],
          id: 87807,
          updatedAtTimestamp: 1655278919,
        },
        {
          tournament: {
            name: 'World Cup, Group H',
            slug: 'world-cup-group-h',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              id: 16,
              displayInverseHomeAwayTeams: false,
            },
            priority: 542,
            id: 3961,
          },
          type: 'total',
          name: 'Group H',
          descriptions: [],
          tieBreakingRule: {
            text: 'In the event that two (or more) teams finish with an equal number of points, the following rules break the tie: 1. Goal difference 2. Goals scored 3. Head-to-head',
            id: 38,
          },
          rows: [
            {
              team: {
                name: 'Ghana',
                slug: 'ghana',
                shortName: 'Ghana',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 63482,
                nameCode: 'GHA',
                ranking: 60,
                disabled: false,
                national: true,
                type: 0,
                id: 4764,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#ffff00',
                  text: '#ffff00',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 1,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709021,
            },
            {
              team: {
                name: 'South Korea',
                slug: 'south-korea',
                shortName: 'South Korea',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 20345,
                nameCode: 'KOR',
                ranking: 28,
                national: true,
                type: 0,
                id: 4735,
                teamColors: {
                  primary: '#ff0000',
                  secondary: '#0000ff',
                  text: '#0000ff',
                },
              },
              descriptions: [],
              promotion: {
                text: 'Playoffs',
                id: 6,
              },
              position: 2,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709022,
            },
            {
              team: {
                name: 'Portugal',
                slug: 'portugal',
                shortName: 'Portugal',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 337493,
                nameCode: 'POR',
                ranking: 9,
                national: true,
                type: 0,
                id: 4704,
                teamColors: {
                  primary: '#cc0000',
                  secondary: '#66cc66',
                  text: '#66cc66',
                },
              },
              descriptions: [],
              position: 3,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709023,
            },
            {
              team: {
                name: 'Uruguay',
                slug: 'uruguay',
                shortName: 'Uruguay',
                gender: 'M',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                userCount: 74808,
                nameCode: 'URU',
                ranking: 13,
                disabled: false,
                national: true,
                type: 0,
                id: 4725,
                teamColors: {
                  primary: '#7eacfe',
                  secondary: '#000000',
                  text: '#000000',
                },
              },
              descriptions: [],
              position: 4,
              matches: 0,
              wins: 0,
              losses: 0,
              draws: 0,
              scoresFor: 0,
              scoresAgainst: 0,
              points: 0,
              id: 709024,
            },
          ],
          id: 87808,
          updatedAtTimestamp: 1655278919,
        },
      ],
    };

    try {
      this.insertNationalTeams(response);
    } catch (error) {
      console.log('Error while inserting nationalTeams, error: ' + error);
    }

    return response;
  }

  async getMatchesByRound(round: string, slugName: string) {
    console.log('Round: ' + round);
    console.log('Slug name: ' + slugName);
    // let response;

    // if (slugName != 'group-faze') {
    //   response = await lastValueFrom(
    //     this.httpService.get(
    //       `${configService.getValue(
    //         'MATCHES_BY_ROUND',
    //       )}/${round}/slug/${slugName}`,
    //     ),
    //   );
    // } else {
    //   response = await lastValueFrom(
    //     this.httpService.get(
    //       `${configService.getValue('MATCHES_BY_ROUND')}/${+round}`,
    //     ),
    //   );
    // }

    // const data: GetMatchesByRoundResponseDto = response.data;
    // return data;

    const response = {
      events: [
        {
          tournament: {
            name: 'World Cup, Group A',
            slug: 'world-cup-group-a',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 549,
            id: 3954,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'hVbsRVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Qatar',
            slug: 'qatar',
            shortName: 'Qatar',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 13036,
            nameCode: 'QAT',
            ranking: 49,
            national: true,
            type: 0,
            id: 4792,
            subTeams: [],
            teamColors: {
              primary: '#660000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          awayTeam: {
            name: 'Ecuador',
            slug: 'ecuador',
            shortName: 'Ecuador',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 29169,
            nameCode: 'ECU',
            ranking: 44,
            disabled: false,
            national: true,
            type: 0,
            id: 4757,
            subTeams: [],
            teamColors: {
              primary: '#ffff00',
              secondary: '#000063',
              text: '#000063',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230541,
          startTimestamp: 1668960000,
          slug: 'qatar-ecuador',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group A',
            slug: 'world-cup-group-a',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 549,
            id: 3954,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'fUbsOUb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Senegal',
            slug: 'senegal',
            shortName: 'Senegal',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 80038,
            nameCode: 'SEN',
            ranking: 18,
            disabled: false,
            national: true,
            type: 0,
            id: 4739,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#047151',
              text: '#047151',
            },
          },
          awayTeam: {
            name: 'Netherlands',
            slug: 'netherlands',
            shortName: 'Netherlands',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 147330,
            nameCode: 'NED',
            ranking: 8,
            disabled: false,
            national: true,
            type: 0,
            id: 4705,
            subTeams: [],
            teamColors: {
              primary: '#ff6600',
              secondary: '#281fe0',
              text: '#281fe0',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230533,
          startTimestamp: 1669046400,
          slug: 'senegal-netherlands',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group B',
            slug: 'world-cup-group-b',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 548,
            id: 3955,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'nUbsqVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'England',
            slug: 'england',
            shortName: 'England',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 276219,
            nameCode: 'ENG',
            ranking: 5,
            national: true,
            type: 0,
            id: 4713,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#cc0000',
              text: '#cc0000',
            },
          },
          awayTeam: {
            name: 'Iran',
            slug: 'iran',
            shortName: 'Iran',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 32163,
            nameCode: 'IRN',
            ranking: 23,
            national: true,
            type: 0,
            id: 4766,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#cc0000',
              text: '#cc0000',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230543,
          startTimestamp: 1669035600,
          slug: 'iran-england',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group B',
            slug: 'world-cup-group-b',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 548,
            id: 3955,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'cUbszUb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'USA',
            slug: 'usa',
            shortName: 'USA',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 39017,
            nameCode: 'USA',
            ranking: 14,
            disabled: false,
            national: true,
            type: 0,
            id: 4724,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#ff0000',
              text: '#ff0000',
            },
          },
          awayTeam: {
            name: 'Wales',
            slug: 'wales',
            shortName: 'Wales',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 45040,
            nameCode: 'WAL',
            ranking: 19,
            disabled: false,
            national: true,
            type: 0,
            id: 4702,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#00813c',
              text: '#00813c',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230548,
          startTimestamp: 1669057200,
          slug: 'usa-wales',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group C',
            slug: 'world-cup-group-c',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 547,
            id: 3956,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'uWbsJWb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Argentina',
            slug: 'argentina',
            shortName: 'Argentina',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 393806,
            nameCode: 'ARG',
            ranking: 3,
            national: true,
            type: 0,
            id: 4819,
            subTeams: [],
            teamColors: {
              primary: '#66ccff',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          awayTeam: {
            name: 'Saudi Arabia',
            slug: 'saudi-arabia',
            shortName: 'Saudi Arabia',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 21522,
            nameCode: 'KSA',
            ranking: 53,
            national: true,
            type: 0,
            id: 4834,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#008000',
              text: '#008000',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230528,
          startTimestamp: 1669111200,
          slug: 'saudi-arabia-argentina',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group C',
            slug: 'world-cup-group-c',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 547,
            id: 3956,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'dUbsGVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Mexico',
            slug: 'mexico',
            shortName: 'Mexico',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 56063,
            nameCode: 'MEX',
            ranking: 12,
            national: true,
            type: 0,
            id: 4781,
            subTeams: [],
            teamColors: {
              primary: '#1a4d3e',
              secondary: '#960000',
              text: '#960000',
            },
          },
          awayTeam: {
            name: 'Poland',
            slug: 'poland',
            shortName: 'Poland',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 88729,
            nameCode: 'POL',
            ranking: 26,
            disabled: false,
            national: true,
            type: 0,
            id: 4703,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#ff0000',
              text: '#ff0000',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230565,
          startTimestamp: 1669132800,
          slug: 'mexico-poland',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group D',
            slug: 'world-cup-group-d',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 546,
            id: 3957,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'BObsEUb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Denmark',
            slug: 'denmark',
            shortName: 'Denmark',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 67654,
            nameCode: 'DEN',
            ranking: 10,
            disabled: false,
            national: true,
            type: 0,
            id: 4476,
            subTeams: [],
            teamColors: {
              primary: '#cc0000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          awayTeam: {
            name: 'Tunisia',
            slug: 'tunisia',
            shortName: 'Tunisia',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 44326,
            nameCode: 'TUN',
            ranking: 30,
            disabled: false,
            national: true,
            type: 0,
            id: 4729,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#cc0033',
              text: '#cc0033',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230576,
          startTimestamp: 1669122000,
          slug: 'tunisia-denmark',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group D',
            slug: 'world-cup-group-d',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 546,
            id: 3957,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'GObsQUb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'France',
            slug: 'france',
            shortName: 'France',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 298495,
            nameCode: 'FRA',
            ranking: 4,
            disabled: false,
            national: true,
            type: 0,
            id: 4481,
            subTeams: [],
            teamColors: {
              primary: '#01509e',
              secondary: '#e30613',
              text: '#e30613',
            },
          },
          awayTeam: {
            name: 'Australia',
            slug: 'australia',
            shortName: 'Australia',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 17309,
            nameCode: 'AUS',
            ranking: 39,
            national: true,
            type: 0,
            id: 4741,
            subTeams: [],
            teamColors: {
              primary: '#ffcc00',
              secondary: '#2d324b',
              text: '#2d324b',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230563,
          startTimestamp: 1669143600,
          slug: 'australia-france',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group E',
            slug: 'world-cup-group-e',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 545,
            id: 3958,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'lUbsvVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Germany',
            slug: 'germany',
            shortName: 'Germany',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 249619,
            nameCode: 'GER',
            ranking: 11,
            national: true,
            type: 0,
            id: 4711,
            subTeams: [],
            teamColors: {
              primary: '#ffffff',
              secondary: '#000000',
              text: '#000000',
            },
          },
          awayTeam: {
            name: 'Japan',
            slug: 'japan',
            shortName: 'Japan',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 28568,
            nameCode: 'JPN',
            ranking: 24,
            national: true,
            type: 0,
            id: 4770,
            subTeams: [],
            teamColors: {
              primary: '#000080',
              secondary: '#ed1b24',
              text: '#ed1b24',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230562,
          startTimestamp: 1669208400,
          slug: 'japan-germany',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group E',
            slug: 'world-cup-group-e',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 545,
            id: 3958,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'YTbsgVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Spain',
            slug: 'spain',
            shortName: 'Spain',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 273147,
            nameCode: 'ESP',
            ranking: 6,
            national: true,
            type: 0,
            id: 4698,
            subTeams: [],
            teamColors: {
              primary: '#cc0000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          awayTeam: {
            name: 'Costa Rica',
            slug: 'costa-rica',
            shortName: 'Costa Rica',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 17002,
            nameCode: 'CRC',
            ranking: 34,
            disabled: false,
            national: true,
            type: 0,
            id: 4756,
            subTeams: [],
            teamColors: {
              primary: '#ed1c24',
              secondary: '#2366b3',
              text: '#2366b3',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230571,
          startTimestamp: 1669219200,
          slug: 'costa-rica-spain',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group F',
            slug: 'world-cup-group-f',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 544,
            id: 3959,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'pUbsDVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Morocco',
            slug: 'morocco',
            shortName: 'Morocco',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 83019,
            nameCode: 'MAR',
            ranking: 22,
            disabled: false,
            national: true,
            type: 0,
            id: 4778,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#006600',
              text: '#006600',
            },
          },
          awayTeam: {
            name: 'Croatia',
            slug: 'croatia',
            shortName: 'Croatia',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 122675,
            nameCode: 'CRO',
            ranking: 15,
            disabled: false,
            national: true,
            type: 0,
            id: 4715,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230570,
          startTimestamp: 1669197600,
          slug: 'morocco-croatia',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group F',
            slug: 'world-cup-group-f',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 544,
            id: 3959,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'rUbscVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Belgium',
            slug: 'belgium',
            shortName: 'Belgium',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 181693,
            nameCode: 'BEL',
            ranking: 2,
            national: true,
            type: 0,
            id: 4717,
            subTeams: [],
            teamColors: {
              primary: '#ff0033',
              secondary: '#000000',
              text: '#000000',
            },
          },
          awayTeam: {
            name: 'Canada',
            slug: 'canada',
            shortName: 'Canada',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 18869,
            nameCode: 'CAN',
            ranking: 43,
            national: true,
            type: 0,
            id: 4752,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230559,
          startTimestamp: 1669230000,
          slug: 'canada-belgium',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group G',
            slug: 'world-cup-group-g',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 543,
            id: 3960,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'ZTbsbVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Switzerland',
            slug: 'switzerland',
            shortName: 'Switzerland',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 56160,
            nameCode: 'SUI',
            ranking: 16,
            disabled: false,
            national: true,
            type: 0,
            id: 4699,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          awayTeam: {
            name: 'Cameroon',
            slug: 'cameroon',
            shortName: 'Cameroon',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 45784,
            nameCode: 'CMR',
            ranking: 38,
            disabled: false,
            national: true,
            type: 0,
            id: 4751,
            subTeams: [],
            teamColors: {
              primary: '#006633',
              secondary: '#d01124',
              text: '#d01124',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230569,
          startTimestamp: 1669284000,
          slug: 'cameroon-switzerland',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group G',
            slug: 'world-cup-group-g',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 543,
            id: 3960,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'YUbsfCc',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Brazil',
            slug: 'brazil',
            shortName: 'Brazil',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 407523,
            nameCode: 'BRA',
            ranking: 1,
            national: true,
            type: 0,
            id: 4748,
            subTeams: [],
            teamColors: {
              primary: '#ffff00',
              secondary: '#009933',
              text: '#009933',
            },
          },
          awayTeam: {
            name: 'Serbia',
            slug: 'serbia',
            shortName: 'Serbia',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 54322,
            nameCode: 'SRB',
            ranking: 25,
            national: true,
            type: 0,
            id: 6355,
            subTeams: [],
            teamColors: {
              primary: '#ff0033',
              secondary: '#ffffff',
              text: '#ffffff',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230567,
          startTimestamp: 1669316400,
          slug: 'serbia-brazil',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group H',
            slug: 'world-cup-group-h',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 542,
            id: 3961,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'AUbsKUb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Uruguay',
            slug: 'uruguay',
            shortName: 'Uruguay',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 74808,
            nameCode: 'URU',
            ranking: 13,
            disabled: false,
            national: true,
            type: 0,
            id: 4725,
            subTeams: [],
            teamColors: {
              primary: '#7eacfe',
              secondary: '#000000',
              text: '#000000',
            },
          },
          awayTeam: {
            name: 'South Korea',
            slug: 'south-korea',
            shortName: 'South Korea',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 20345,
            nameCode: 'KOR',
            ranking: 28,
            national: true,
            type: 0,
            id: 4735,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#0000ff',
              text: '#0000ff',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230530,
          startTimestamp: 1669294800,
          slug: 'south-korea-uruguay',
          finalResultOnly: false,
        },
        {
          tournament: {
            name: 'World Cup, Group H',
            slug: 'world-cup-group-h',
            category: {
              name: 'World',
              slug: 'world',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1468,
              flag: 'international',
            },
            uniqueTournament: {
              name: 'World Cup',
              slug: 'world-cup',
              category: {
                name: 'World',
                slug: 'world',
                sport: {
                  name: 'Football',
                  slug: 'football',
                  id: 1,
                },
                id: 1468,
                flag: 'international',
              },
              userCount: 426658,
              hasPositionGraph: false,
              id: 16,
              hasEventPlayerStatistics: true,
              displayInverseHomeAwayTeams: false,
            },
            priority: 542,
            id: 3961,
          },
          roundInfo: {
            round: 1,
          },
          customId: 'eUbsoVb',
          status: {
            code: 0,
            description: 'Not started',
            type: 'notstarted',
          },
          winnerCode: 0,
          homeTeam: {
            name: 'Portugal',
            slug: 'portugal',
            shortName: 'Portugal',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 337493,
            nameCode: 'POR',
            ranking: 9,
            national: true,
            type: 0,
            id: 4704,
            subTeams: [],
            teamColors: {
              primary: '#cc0000',
              secondary: '#66cc66',
              text: '#66cc66',
            },
          },
          awayTeam: {
            name: 'Ghana',
            slug: 'ghana',
            shortName: 'Ghana',
            gender: 'M',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            userCount: 63482,
            nameCode: 'GHA',
            ranking: 60,
            disabled: false,
            national: true,
            type: 0,
            id: 4764,
            subTeams: [],
            teamColors: {
              primary: '#ff0000',
              secondary: '#ffff00',
              text: '#ffff00',
            },
          },
          homeScore: {},
          awayScore: {},
          time: {},
          changes: {
            changeTimestamp: 0,
          },
          hasGlobalHighlights: false,
          id: 10230534,
          startTimestamp: 1669305600,
          slug: 'ghana-portugal',
          finalResultOnly: false,
        },
      ],
      hasNextPage: false,
    };

    try {
      this.insertMatches(response.events);
    } catch (error) {
      console.log('Error inserting matches, error: ' + error);
    }

    return response;
  }

  private insertNationalTeams(data) {
    let nationalTeam: NationalTeamRequestDto;

    for (const group of data.standings) {
      for (const teamInfo of group.rows) {
        nationalTeam = {
          name: teamInfo.team.name,
          group: group.name,
          standingsPosition: teamInfo.position,
          matchesPlayed: teamInfo.matches,
          wins: teamInfo.wins,
          draws: teamInfo.draws,
          losses: teamInfo.losses,
          points: teamInfo.points,
        };

        this.nationalTeamRepository.save(nationalTeam);
      }
    }
  }

  private insertMatches(events) {
    let match: MatchDto;
    for (const event of events) {
      match = {
        id: event.customId,
        round: event.roundInfo.round,
        status: event.status.description,
        winner_code: event.winnerCode,
        homeTeam: event.homeTeam,
        awayTeam: event.awayTeam,
        home_score: event.homeScore.current,
        away_score: event.awayScore.current,
      };

      this.matchRepository.save(match);
    }
  }
}
